name: clean-air-project
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - platformio==6.1.15
      - esptool==4.7.0
      - requests==2.32.3
      - urllib3==2.2.2
      - pydantic==2.7.1
      - numpy==1.26.4
      - pandas==2.2.2
      - matplotlib==3.8.4
      - paho-mqtt==2.1.0
      - fastapi==0.111.0
      - uvicorn==0.30.1
      - pyyaml==6.0.1
      - pyserial==3.5
